{{- if not .Values.devMode }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esthesis-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    {{- if .Values.esthesisUiCertManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.esthesisUiCertManagerClusterIssuer | quote }}
    {{- end }}
    {{- if .Values.esthesisUiCertManagerIssuer }}
    cert-manager.io/issuer: {{ .Values.esthesisUiCertManagerIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.esthesisIngressName }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: esthesis-core-ui-service
                port:
                  number: 80
  {{- if or .Values.esthesisUiCertManagerClusterIssuer .Values.esthesisUiCertManagerIssuer }}
  tls:
    - hosts:
        - {{ .Values.esthesisIngressName }}
      secretName: esthesis-ui-ingress-tls
  {{- end }}
  {{- end }}
