##################################################################################################
# Global values
##################################################################################################
devMode: false
domain: ""
esthesisVersion: "3.0.59-SNAPSHOT"
oidcRedirectUri: ""
timezone: "Europe/Athens"
imagePullSecret: "regcred"
ingressClassName: ""

# Enable/disable charts
charts_enabled:
  kafka-ui: true
  orion: true
  docker-registry-ui: true
  grafana-tempo: true
  grafana-loki: true
  grafana: true
  ingress-nginx: false
  ollama: true

##################################################################################################
# Accounts
##################################################################################################
esthesisAdminUsername: esthesis-admin
esthesisAdminPassword: esthesis-admin
esthesisSystemUsername: esthesis-system
esthesisSystemPassword: esthesis-system

##################################################################################################
# Mosquitto
##################################################################################################
mosquittoEnabled: true
mosquittoServiceType: LoadBalancer
mosquittoMutualTls: false
mosquittoSuperuser: esthesis
mosquittoCaCert: ""
mosquittoServerCert: ""
mosquittoServerKey: ""

##################################################################################################
# Redis
##################################################################################################
redis:
  fullnameOverride: "redis"
  global:
    imagePullSecrets:
      - name: "regcred"
  auth:
    password: esthesis-system

##################################################################################################
# MongoDB
##################################################################################################
psmdb-db:
  nameOverride: "mongodb"
  imagePullSecrets:
    - name: "regcred"
  clusterServiceDNSSuffix: cluster.local
  replsets:
    rs0:
      size: 1
  users:
    - name: esthesis-system
      db: admin
      passwordSecretRef:
        name: esthesis-system
        key: password
      roles:
        - name: dbAdmin
          db: esthesiscore

##################################################################################################
# Cloudnative PostgreSQL
##################################################################################################

pg_db:
  fullnameOverride: "postgres"
  type: postgresql
  cluster:
    instances: 1
    imagePullSecrets:
      - name: regcred
    storage:
      size: 10Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 256Mi
  imageCatalog:
    enabled: false
  poolers:
    - name: rw
      type: rw
      poolMode: transaction
      instances: 1
      parameters:
        max_client_conn: "1000"
        default_pool_size: "100"

##################################################################################################
# Kafka (Strimzi)
##################################################################################################
strimzi-kafka-operator: {}

kafka:
  name: kafka
  replicas: 1
  version: "3.9.0"
  metadataVersion: "3.9-IV0"
  storage:
    type: persistent-claim
    size: 20Gi
    class: "" # use your StorageClass name or leave empty
  auth:
    type: scram-sha-512
  config:
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    default.replication.factor: 1
    min.insync.replicas: 1
    auto.create.topics.enable: "false"
  topics:
    - { name: esthesis-command-reply, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-telemetry, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-metadata, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-app-unicast, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-app-broadcast, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-ping, partitions: 1, replicationFactor: 1 }
    - { name: esthesis-command-request, partitions: 1, replicationFactor: 1 }
  users:
    - name: esthesis-system
      auth: scram-sha-512
      # authorization:
      #   acls:
      #     - operation: All
      #       resource:
      #         type: cluster

##################################################################################################
# Kafka UI (Provectus)
##################################################################################################
kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka
          bootstrapServers: "kafka-kafka-bootstrap:9092"
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: >
              org.apache.kafka.common.security.scram.ScramLoginModule required
              username="esthesis-system" password="esthesis-system";

##################################################################################################
# Keycloak (codecentric/keycloakx)
##################################################################################################
keycloakx:
  fullnameOverride: "keycloak"
  image:
    tag: "24.0.5"
  imagePullSecrets: []
  replicas: 1
  service:
    httpPort: 8080
  args:
    - start
  extraEnv: |
    - name: KC_HOSTNAME
      value: https://keycloak.esthesis-dev.eurodyn.com/auth
    - name: KC_HOSTNAME_ADMIN
      value: https://keycloak.esthesis-dev.eurodyn.com/auth
    - name: KEYCLOAK_ADMIN
      value: esthesis-system
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: esthesis-system
    - name: KC_PROXY
      value: "passthrough"
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  database:
    vendor: postgres
    hostname: postgres-pooler-rw
    port: 5432
    database: keycloak
    username: keycloak
    password: esthesis-system
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    servicePort: "http"
    rules:
      - host: "keycloak.esthesis-dev.eurodyn.com"
        paths:
          - path: "/auth/"
            pathType: Prefix
    tls:
      - hosts:
          - keycloak.esthesis-dev.eurodyn.com

##################################################################################################
# Camunda
##################################################################################################
camunda-platform:
  global:
    zeebeClusterName: "zeebe"
    image:
      pullSecrets:
        - name: "regcred"
    identity:
      keycloak:
        url:
          protocol: "http"
          host: "keycloak-headless"
          port: "8080"
      auth:
        enabled: false
  operate:
    enabled: false
  optimize:
    enabled: false
  tasklist:
    enabled: false
  identity:
    enabled: false
  identityKeycloak:
    enabled: false
  webModeler:
    enabled: false
  connectors:
    enabled: false
  zeebe:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  zeebeGateway:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  elasticsearch:
    enabled: true
    global:
      imagePullSecrets:
        - regcred
    image:
      repository: bitnamilegacy/elasticsearch
    sysctlImage:
      repository: bitnamilegacy/os-shell
    metrics:
      image:
        repository: bitnamilegacy/elasticsearch-exporter
    volumePermissions:
      image:
        repository: bitnamilegacy/os-shell
    copyTlsCerts:
      image:
        repository: bitnamilegacy/os-shell
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    replicas: 1
    minimumMasterNodes: 1

##################################################################################################
# InfluxDB2 (InfluxData)
##################################################################################################
influxdb2:
  fullnameOverride: "influxdb"
  image:
    pullSecrets:
      - regcred
  adminUser:
    organization: esthesis
    bucket: esthesis
    user: esthesis-system
    password: esthesis-system
    token: "918UdZNzKNEf7YeL7efV"
  persistence:
    enabled: true
    size: 32Gi

##################################################################################################
# Grafana (official)
##################################################################################################
grafana:
  fullnameOverride: "grafana"
  adminUser: esthesis-system
  adminPassword: esthesis-system
  image:
    pullSecrets: []

##################################################################################################
# Loki (official)
##################################################################################################
loki:
  fullnameOverride: "grafana-loki"
  imagePullSecrets:
    - name: "regcred"
  # These 3 variables are necessary if you wish to enable loki-gateway
  #global:
  #  dnsNamespace: kube-system
  #  clusterDomain: esthesis-dev.eurodyn.com
  #  dnsService: rke2-coredns-rke2-coredns
  promtail:
    enabled: true
  test:
    enabled: false
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  gateway:
    enabled: false
    nginxConfig:
      enableIPv6: false
  loki:
    storage:
      type: filesystem
    schemaConfig:
      configs:
        - from: "2025-09-01" # use today's date or slightly earlier for a fresh cluster
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

##################################################################################################
# Tempo (official)
##################################################################################################
tempo:
  fullnameOverride: "grafana-tempo"
  tempo:
    traces:
      jaeger:
        grpc: false
        thriftHttp: false
      otlp:
        grpc: true

##################################################################################################
# Ingress-NGINX (official)
##################################################################################################
ingress-nginx:
  fullnameOverride: "ingress-nginx"
  controller:
    scope:
      enabled: false
      namespace: default
    service:
      externalIPs:
        - "192.168.1.1"
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "*.esthesis"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    ingressClassResource:
      name: "nginx-default"

##################################################################################################
# Docker Registry UI
##################################################################################################
docker-registry-ui:
  fullnameOverride: "docker-registry-ui"
  global:
    name: docker-registry
    imagePullSecrets: []
  ui:
    proxy: true
    deleteImages: true
  registry:
    enabled: true
    service:
      type: NodePort
      nodePort: ""

##################################################################################################
# Ollama
##################################################################################################
ollama:
  fullnameOverride: "ollama"
  ollama:
    models:
      pull:
        - "qwen3:0.6b"
        - "nomic-embed-text"
      run:
        - "qwen3:0.6b"
