##################################################################################################
# Global values
##################################################################################################
devMode: false
domain: ""
esthesisVersion: "3.0.59-SNAPSHOT"
oidcRedirectUri: ""
timezone: "Europe/Athens"
imagePullSecret: "regcred"
ingressClassName: ""

# Enable/disable charts
charts_enabled:
  kafka-ui: false
  orion: false
  docker-registry-ui: false
  grafana-tempo: false
  grafana-loki: false
  grafana: false
  ingress-nginx: false
  ollama: false

##################################################################################################
# Accounts
##################################################################################################
esthesisAdminUsername: esthesis-admin
esthesisAdminPassword: esthesis-admin
esthesisSystemUsername: esthesis-system
esthesisSystemPassword: esthesis-system

##################################################################################################
# Mosquitto
##################################################################################################
mosquittoEnabled: true
mosquittoServiceType: LoadBalancer
mosquittoMutualTls: false
mosquittoSuperuser: esthesis
mosquittoCaCert: ""
mosquittoServerCert: ""
mosquittoServerKey: ""

##################################################################################################
# Redis
##################################################################################################
redis:
  fullnameOverride: "redis"
  global:
    imagePullSecrets:
        - name: "regcred"
  auth:
    password: esthesis-system

##################################################################################################
# MongoDB (Percona Operator + DB)
##################################################################################################
psmdb-operator:
  imagePullSecrets:
    - name: "regcred"

psmdb-db:
  name: "mongodb"
  imagePullSecrets:
    - name: "regcred"
  clusterServiceDNSSuffix: cluster.local
  replsets:
    rs0:
      size: 1
  users:
    - name: esthesis-system
      db: admin
      passwordSecretRef:
        name: esthesis-system
        key: password
      roles:
        - name: dbAdmin
          db: esthesiscore

pg-operator:
  imagePullSecrets:
    - name: "regcred"

pg-db:
  databaseInitSQL:
    key: init.sql
    name: postgres-dt-init
  imagePullSecrets:
    - name: "regcred"
  instances:
    - name: instance1
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 1.0
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  proxy:
    pgBouncer:
      replicas: 1
  backups:
    enabled: false

##################################################################################################
# Kafka (Strimzi)
##################################################################################################
strimzi-kafka-operator: {}

kafka:
  name: kafka
  namespace: default
  kraft:
    enabled: true
  replicas: 3
  storage:
    type: persistent-claim
    size: 20Gi
    class: ""          # set StorageClass if needed
  auth:
    type: scram-sha-512
    users:
      - name: esthesis-system
        password: esthesis-system
  topics:
    - name: esthesis-command-reply
      partitions: 3
      replicationFactor: 3
    - name: esthesis-telemetry
      partitions: 3
      replicationFactor: 3
    - name: esthesis-metadata
      partitions: 3
      replicationFactor: 3
    - name: esthesis-app-unicast
      partitions: 3
      replicationFactor: 3
    - name: esthesis-app-broadcast
      partitions: 3
      replicationFactor: 3
    - name: esthesis-ping
      partitions: 3
      replicationFactor: 3
    - name: esthesis-command-request
      partitions: 3
      replicationFactor: 3

  brokerConfig:
    "offsets.topic.replication.factor": "3"
    "transaction.state.log.replication.factor": "3"

##################################################################################################
# Kafka UI (Provectus)
##################################################################################################
kafka-ui:
  fullnameOverride: "kafka-ui"
  imagePullSecrets: []
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka
          bootstrapServers: "kafka-kafka-bootstrap:9092"
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: >
              org.apache.kafka.common.security.scram.ScramLoginModule required
              username="esthesis-system" password="esthesis-system";

##################################################################################################
# Keycloak (codecentric/keycloakx)
##################################################################################################
keycloakx:
  fullnameOverride: "keycloak"
  image:
    pullSecrets: []
  replicas: 1
  service:
    httpPort: 8080
  args:
    - start
  extraEnv: |
    - name: KC_HOSTNAME
      value: https://keycloak.esthesis-dev.eurodyn.com/auth
    - name: KC_HOSTNAME_ADMIN
      value: https://keycloak.esthesis-dev.eurodyn.com/auth
    - name: KEYCLOAK_ADMIN
      value: esthesis-system
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: esthesis-system
    - name: KC_PROXY
      value: "passthrough"
  database:
    vendor: postgres
    hostname: esthesis-deps-pg-db-pgbouncer
    port: 5432
    database: keycloak
    username: postgres
    password: esthesis-system
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    servicePort: "http"
    rules:
      - host: 'keycloak.esthesis-dev.eurodyn.com'
        paths:
          - path: '/auth/'
            pathType: Prefix
    tls:
      - hosts:
        - keycloak.esthesis-dev.eurodyn.com


##################################################################################################
# Camunda
##################################################################################################
camunda-platform:
  global:
    zeebeClusterName: "zeebe"
    image:
      pullSecrets:
        - name: "regcred"
    identity:
      keycloak:
        url:
          protocol: "http"
          host: "keycloak-headless"
          port: "8080"
      auth:
        enabled: false
  operate:
    enabled: false
  optimize:
    enabled: false
  tasklist:
    enabled: false
  identity:
    enabled: false
  identityKeycloak:
    enabled: false
  webModeler:
    enabled: false
  connectors:
    enabled: false
  zeebe:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  zeebeGateway:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
  elasticsearch:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

##################################################################################################
# InfluxDB2 (InfluxData)
##################################################################################################
influxdb2:
  fullnameOverride: "influxdb"
  image:
    pullSecrets:
      - regcred
  adminUser:
    organization: esthesis
    bucket: esthesis
    user: esthesis-system
    password: esthesis-system
    token: "918UdZNzKNEf7YeL7efV"
  persistence:
    enabled: true
    size: 32Gi

##################################################################################################
# Grafana (official)
##################################################################################################
grafana:
  fullnameOverride: "grafana"
  adminUser: esthesis-system
  adminPassword: esthesis-system
  image:
    pullSecrets: []

##################################################################################################
# Loki (official)
##################################################################################################
loki:
  fullnameOverride: "grafana-loki"
  promtail:
    enabled: true

##################################################################################################
# Tempo (official)
##################################################################################################
tempo:
  fullnameOverride: "grafana-tempo"
  tempo:
    traces:
      jaeger:
        grpc: false
        thriftHttp: false
      otlp:
        grpc: true

##################################################################################################
# Ingress-NGINX (official)
##################################################################################################
ingress-nginx:
  fullnameOverride: "ingress-nginx"
  controller:
    scope:
      enabled: false
      namespace: default
    service:
      externalIPs:
        - "192.168.1.1"
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "*.esthesis"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    ingressClassResource:
      name: "nginx-default"

##################################################################################################
# Docker Registry UI
##################################################################################################
docker-registry-ui:
  fullnameOverride: "docker-registry-ui"
  global:
    name: docker-registry
    imagePullSecrets: []
  ui:
    proxy: true
    deleteImages: true
  registry:
    enabled: true
    service:
      type: NodePort
      nodePort: ""

##################################################################################################
# Ollama
##################################################################################################
ollama:
  fullnameOverride: "ollama"
  ollama:
    models:
      pull:
        - "qwen3:0.6b"
        - "nomic-embed-text"
      run:
        - "qwen3:0.6b"
