##################################################################################################
# Global values
##################################################################################################
devMode: true

# memcached:1.6.22-debian-11-r1

domain: esthesis
esthesisVersion: "3.0.59-SNAPSHOT"
#esthesisLocalCharts: true
esthesisReportedOidcPostLogoutUrl: http://localhost:4200/logged-out
oidcRedirectUri: http://localhost:4200/callback
timezone: "Europe/Athens"
ingressClassName:
imagePullSecret: ""

# Enable/disable charts
charts_enabled:
  kafka-ui: true
  orion: false
  docker-registry-ui: true
  grafana-tempo: true
  grafana-loki: true
  grafana: true
  ingress-nginx: false
  ollama: true

##################################################################################################
# Accounts to be used throughout charts.
##################################################################################################
esthesisAdminUsername: esthesis-admin
esthesisAdminPassword: esthesis-admin
esthesisSystemUsername: esthesis-system
esthesisSystemPassword: esthesis-system

##################################################################################################
# Mosquitto Values
##################################################################################################
mosquittoEnabled: true
mosquittoServiceType: ClusterIP
mosquittoMutualTls: false
mosquittoSuperuser: esthesis
mosquittoCaCert: ""
mosquittoServerCert: ""
mosquittoServerKey: ""

# Redis configuration
redis:
  fullnameOverride: "redis"
  image:
    repository: bitnamilegacy/redis
    pullSecrets: []
  architecture: standalone
  auth:
    password: esthesis-system
  sentinel:
    image:
      repository: bitnamilegacy/redis-sentinel
  metrics:
    image:
      repository: bitnamilegacy/redis-exporter
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  sysctl:
    image:
      repository: bitnamilegacy/bitnami-shell-archived

# MongoDB configuration
mongodb:
  fullnameOverride: "mongodb"
  image:
    repository: bitnamilegacy/mongodb
    pullSecrets: []
    debug: true
  tls:
    image:
      repository: bitnamilegacy/nginx
  externalAccess:
    image:
      repository: bitnamilegacy/kubectl
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/mongodb-exporter
  architecture: replicaset
  replicaCount: 1
  auth:
    rootPassword: esthesis-system
    replicaSetKey: "ZXN0aGVzaXMtc3lzdGVt" # Base64 encoded string "esthesis-system"
    usernames:
      - "esthesis-system"
    passwords:
      - "esthesis-system"
    databases:
      - "esthesiscore"
  initdbScripts:
    init-db.js: |
      use esthesiscore
      db.grantRolesToUser("esthesis-system", ["dbAdmin"])

# Kafka configuration
kafka:
  fullnameOverride: "kafka"
  image:
    repository: bitnamilegacy/kafka
    pullSecrets: []
  provisioning:
    enabled: true
    topics:
      - name: esthesis-command-reply
        partitions: 1
        replicationFactor: 1
      - name: esthesis-telemetry
        partitions: 1
        replicationFactor: 1
      - name: esthesis-metadata
        partitions: 1
        replicationFactor: 1
      - name: esthesis-app-unicast
        partitions: 1
        replicationFactor: 1
      - name: esthesis-app-broadcast
        partitions: 1
        replicationFactor: 1
      - name: esthesis-ping
        partitions: 1
        replicationFactor: 1
      - name: esthesis-command-request
        partitions: 1
        replicationFactor: 1
  kraft:
    clusterId: "M3Q1ZTNlMWFhMTgyNDhiZj"
  sasl:
    interbroker:
      password: "esthesis-system"
    controller:
      password: "esthesis-system"
    client:
      users:
        - "esthesis-system"
      passwords:
        - "esthesis-system"
  controller:
    replicaCount: 1
  externalAccess:
    image:
      repository: bitnamilegacy/kubectl
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/kafka-exporter-archived
  jmx:
    image: 
      repository: bitnamilegacy/jmx-exporter
  extraConfig: |
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1

# Keycloak configuration
keycloak:
  fullnameOverride: "keycloak"
  global:
    imagePullSecrets: []
  image:
    repository: bitnamilegacy/keycloak
  proxyHeaders: xforwarded
  production: true
  auth:
    adminUser: esthesis-system
    adminPassword: esthesis-system
  postgresql:
    fullnameOverride: "postgresql"
    auth:
      postgresPassword: "esthesis-system"
      password: "esthesis-system"
  readinessProbe:
    timeoutSeconds: 60
  keycloakConfigCli:
    image:
        repository: bitnamilegacy/keycloak-config-cli

# Camunda configuration
camunda-platform:
  global:
    zeebeClusterName: "zeebe"
    image:
      pullSecrets: []
    identity:
      keycloak:
        url:
          protocol: "http"
          host: "keycloak-headless"
          port: "8080"
      auth:
        enabled: false
  operate:
    enabled: false
  optimize:
    enabled: false
  tasklist:
    enabled: false
  identity:
    enabled: false
  identityKeycloak:
    enabled: false
    image:
      repository: bitnamilegacy/keycloak
    postgresql:
      image:
        repository: bitnamilegacy/postgresql
      volumePermissions:
        image:
          repository: bitnamilegacy/os-shell
      metrics:
        image:
          repository: bitnamilegacy/postgres-exporter
    keycloakConfigCli:
      image:
        repository: bitnamilegacy/keycloak-config-cli
  webModeler:
    enabled: false
  connectors:
    enabled: false
  zeebe:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    clusterSize: 1
    replicationFactor: 1
  zeebeGateway:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    replicas: 1
  elasticsearch:
    enabled: true
    image:
      repository: bitnamilegacy/elasticsearch
    sysctlImage:
      repository: bitnamilegacy/os-shell
    metrics:
      image:
        repository: bitnamilegacy/elasticsearch-exporter
    volumePermissions:
      image:
        repository: bitnamilegacy/os-shell
    copyTlsCerts:
      image:
        repository: bitnamilegacy/os-shell
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
    replicas: 1
    minimumMasterNodes: 1
  identityPostgresql:
    image:
      repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/postgres-exporter
  # WebModeler PostgreSQL configuration
  webModelerPostgresql:
    image:
      repository: bitnamilegacy/postgresql

# InfluxDB configuration
influxdb:
  fullnameOverride: "influxdb"
  global:
    imagePullSecrets: []
  image:
    repository: bitnamilegacy/influxdb
  auth:
    admin:
      username: esthesis-system
      password: esthesis-system
      token: "918UdZNzKNEf7YeL7efV"
    user:
      org: esthesis
      bucket: esthesis
      username: esthesis-system
      password: esthesis-system
  persistence:
    size: "32Gi"
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  uploadProviders:
    google:
      image:
        repository: bitnamilegacy/google-cloud-sdk
    azure:
      image:
        repository: bitnamilegacy/azure-cli
    aws:
      image:
        repository: bitnamilegacy/aws-cli

# Grafana configuration
grafana:
  fullnameOverride: "grafana"
  global:
    imagePullSecrets: []
  image:
    repository: bitnamilegacy/grafana
  admin:
    user: esthesis-system
    password: esthesis-system
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell

# Kafka UI configuration
kafka-ui:
  fullnameOverride: "kafka-ui"
  imagePullSecrets: []
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka
          bootstrapServers: "kafka:9092"
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: PLAIN
            sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=esthesis-system password=esthesis-system;"

# Grafana Loki configuration
grafana-loki:
  fullnameOverride: "grafana-loki"
  global:
    imagePullSecrets: []
  promtail:
    enabled: true
    image:
      repository: bitnamilegacy/promtail-archived
  loki:
    image:
      repository: bitnamilegacy/grafana-loki
  gateway:
    image: 
      repository: bitnamilegacy/nginx
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  memcachedchunks:
    image:
      repository: bitnamilegacy/memcached
  memcachedfrontend:
    image:
      repository: bitnamilegacy/memcached
  memcachedindexqueries:
    image:
      repository: bitnamilegacy/memcached
  memcachedindexwrites:
    image:
      repository: bitnamilegacy/memcached
# Ingress nginx configuration
ingress-nginx:
  fullnameOverride: "ingress-nginx"
  controller:
    scope:
      enabled: false
      namespace: default
    service:
      externalIPs:
        - "192.168.1.1"
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "*.esthesis"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    ingressClassResource:
      name: "nginx-default"

# Docker Registry UI configuration
docker-registry-ui:
  fullnameOverride: "docker-registry-ui"
  global:
    name: docker-registry
    imagePullSecrets: []
  ui:
    proxy: true
    deleteImages: true
  registry:
    enabled: true
    service:
      type: NodePort
      nodePort: ""

# Grafana Tempo configuration
grafana-tempo:
  fullnameOverride: "grafana-tempo"
  global:
    imagePullSecrets: []
  tempo:
    image:
      repository: bitnamilegacy/grafana-tempo
    traces:
      jaeger:
        grpc: false
        thriftHttp: false
      otlp:
        grpc: true # Needed by Quarkus (port 4317)
  query:
    image:
      repository: bitnamilegacy/grafana-tempo-query
  vulture:
    image:
      repository: bitnamilegacy/grafana-tempo-vulture
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell

# Ollama
ollama:
  fullnameOverride: "ollama"
  ollama:
    models:
      pull:
        - "qwen3:0.6b"
        - "nomic-embed-text"
      run:
        - "qwen3:0.6b"
