##################################################################################################
# Strimzi Kafka Operator configuration
##################################################################################################
strimzi-kafka-operator:
  watchNamespaces: []  # Empty = watch all namespaces
  watchAnyNamespace: true

##################################################################################################
# Percona MongoDB Operator configuration
##################################################################################################
psmdb-operator:
  watchNamespace: "*"  # Watch all namespaces

##################################################################################################
# Percona PostgreSQL Operator configuration
##################################################################################################
pg-operator:
  watchNamespace: "*"  # Watch all namespaces
