##################################################################################################
# Strimzi Kafka Operator configuration
##################################################################################################
strimzi-kafka-operator:
  watchNamespaces: [] # Empty = watch all namespaces
  watchAnyNamespace: true
  image:
    imagePullSecrets:
      - name: regcred

##################################################################################################
# Percona MongoDB Operator configuration
##################################################################################################
psmdb-operator:
  watchAllNamespaces: true # Watch all namespaces
  imagePullSecrets:
    - name: regcred

##################################################################################################
# Cloudnative PostgreSQL Operator configuration
##################################################################################################
cloudnative-pg:
  imagePullSecrets:
    - name: regcred
