{{ if not .Values.devMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-core-ui-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-core-ui
  template:
    metadata:
      labels:
        app: esthesis-core-ui
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: esthesis-core-ui
          {{- if .Values.esthesisRegistry }}
          image: "{{ .Values.esthesisRegistry }}/esthesis-core-ui:{{ .Chart.Version }}"
          {{- else }}
          image: "esthesisiot/esthesis-core-ui:{{ .Chart.Version }}"
          {{- end }}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
{{ end }}
