{{ if not .Values.devMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-core-ui-deployment
  annotations:
    configmap.reloader.stakater.com/reload: "esthesis-core-ui-cm"
spec:
  selector:
    matchLabels:
      app: esthesis-core-ui
  template:
    metadata:
      labels:
        app: esthesis-core-ui
    spec:
      containers:
        - name: esthesis-core-ui
          {{- if .esthesisRegistry }}
          image: {{ .esthesisRegistry }}/esthesisiot/esthesis-core-ui:3.0.0-SNAPSHOT
          {{- else }}
          image: esthesisiot/esthesis-core-ui:3.0.0-SNAPSHOT
          {{- end }}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
{{ end }}
