apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esthesis-core-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  rules:
    - host: {{ .Values.esthesisUiIngressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esthesis-core-ui-service
                port:
                  number: 80
