apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esthesis-core-ui-ingress
spec:
  rules:
    - host: {{ .Values.esthesisUiIngressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esthesis-core-ui-service
                port:
                  number: 80
