{{ if not .Values.devMode }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esthesis-core-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    {{- if .Values.esthesisUiCertManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.esthesisUiCertManagerClusterIssuer | quote }}
    {{- end }}
    {{- if .Values.esthesisUiCertManagerIssuer }}
    cert-manager.io/issuer: {{ .Values.esthesisUiCertManagerIssuer | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.esthesisUiIngressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esthesis-core-ui-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apisix-gateway
                port:
                  number: 80
  {{- if or .Values.esthesisUiCertManagerClusterIssuer .Values.esthesisUiCertManagerIssuer }}
  tls:
    - hosts:
        - {{ .Values.esthesisUiIngressHostname }}
      secretName: esthesis-core-ui-tls
  {{- end }}
{{ end }}
