apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui-deployment
  annotations:
    configmap.reloader.stakater.com/reload: "{{ .Release.Name }}-ui-cm"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: esthesis-core-ui
          image: esthesisiot/esthesis-core-ui:3.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/templates/
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-ui-cm
