apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  rules:
    - host: {{ .Values.esthesisUiIngressHostname }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apisix-gateway
                port:
                  number: 80
