apiVersion: v1
kind: Secret
metadata:
  name: esthesis-core-secret
type: Opaque
stringData:
  # The password for B2B communication of esthesis components, or when esthesis communicates with other systems.
  esthesisSystemPassword: {{ .Values.esthesisSystemPassword }}
  # The password for the MongoDB.
  mongoDbPassword: {{ .Values.mongoDbPassword }}
