apiVersion: v2
name: esthesis-core
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: "3.0.34"
appVersion: "3.0.34"
