##################################################################################################
# Environments definitions
##################################################################################################
environments:
  default:
    values:
      - devMode: false
      - redisHosts: {{ if (env "REDIS_HOSTS") }}{{ env "REDIS_HOSTS" }}{{ else }}redis://redis-headless.{{ .Namespace }}.svc.cluster.local:6379{{ end }}
      - mongoDbUrlCluster: {{ if (env "MONGODB_URL_CLUSTER") }}{{ env "MONGODB_URL_CLUSTER" }}{{ else }}mongodb://mongodb-0.mongodb-headless.{{ .Namespace }}.svc.cluster.local:27017,mongodb-1.mongodb-headless.{{ .Namespace }}.svc.cluster.local:27017{{ end }}
      - camundaGatewayUrlCluster: {{ if (env "CAMUNDA_GATEWAY_URL_CLUSTER") }}{{ env "CAMUNDA_GATEWAY_URL_CLUSTER" }}{{ else }}camunda-zeebe-gateway.{{ .Namespace }}.svc.cluster.local:26500{{ end }}
      - kafkaBootstrapServers: {{ if (env "KAFKA_BOOTSTRAP_SERVERS") }}{{ env "KAFKA_BOOTSTRAP_SERVERS" }}{{ else }}kafka.{{ .Namespace }}.svc.cluster.local:9092{{ end }}
      - oidcAuthorityUrlCluster: {{ if (env "OIDC_AUTHORITY_URL_CLUSTER") }}{{ env "OIDC_AUTHORITY_URL_CLUSTER" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis{{ end }}
      - oidcDiscoveryUrlCluster: {{ if (env "OIDC_DISCOVERY_URL_CLUSTER") }}{{ env "OIDC_DISCOVERY_URL_CLUSTER" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis/.well-known/openid-configuration{{ end }} 
      - oidcJwtVerifyLocationCluster: {{ if (env "OIDC_JWT_VERIFY_LOCATION_CLUSTER") }}{{ env "OIDC_JWT_VERIFY_LOCATION_CLUSTER" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis/protocol/openid-connect/certs{{ end }}
      - oidcAuthorityUrlExternal: {{ env "OIDC_AUTHORITY_URL_EXTERNAL" }}
      - esthesisIngressName: {{ env "ESTHESIS_INGRESS_NAME" }}
  dev:
    values:
      - devMode: true
      - camundaGatewayUrlCluster: camunda-zeebe-gateway.esthesis:26500
      - kafkaBootstrapServers: kafka.esthesis:9094
      - oidcAuthorityUrlExternal: https://keycloak.esthesis/realms/esthesis
      - oidcAuthorityUrlCluster: http://keycloak.esthesis/realms/esthesis
      - oidcDiscoveryUrlCluster: http://keycloak.esthesis/realms/esthesis/.well-known/openid-configuration
      - oidcJwtVerifyLocationCluster: http://keycloak.esthesis/realms/esthesis/protocol/openid-connect/certs
      - redisHosts: redis://redis.esthesis:6379
      - esthesisIngressName: "esthesis-ingress"
      - mongoDbUrlCluster: mongodb://mongodb-headless.esthesis:27017

---
##################################################################################################
# The repositories used by this Helmfile.
##################################################################################################
repositories:
  - name: esthesis
    url: https://esthes.is/helm

---
##################################################################################################
# Default values
##################################################################################################
helmDefaults:
  timeout: 1800

---
##################################################################################################
# Default state values
##################################################################################################
values:
  - imagePullSecret: {{ env "IMAGE_PULL_SECRET" }}
  - timezone: {{ env "TIMEZONE" | default "Europe/Athens" }}
  - esthesisLogLevel: {{ env "ESTHESIS_LOG_LEVEL" | default "WARN" }}
  - esthesisAdminUsername: {{ env "ESTHESIS_ADMIN_USERNAME" | default "esthesis-admin" }}
  - esthesisAdminPassword: {{ env "ESTHESIS_ADMIN_PASSWORD" | default "esthesis-admin" }}
  - esthesisSystemUsername: {{ env "ESTHESIS_SYSTEM_USERNAME" | default "esthesis-system" }}
  - esthesisSystemPassword: {{ env "ESTHESIS_SYSTEM_PASSWORD" | default "esthesis-system" }}
  - esthesisRegistry: {{ env "ESTHESIS_REGISTRY_URL" }}
  # MongoDB
  - mongoDbEnabled: {{ env "MONGODB_ENABLED" | default true }}
  - mongoDbDatabase: {{ env "MONGODB_DATABASE" | default "esthesiscore" }}
  - mongoDbUsername: {{ env "MONGODB_USERNAME" | default .StateValues.esthesisSystemUsername }}
  - mongoDbPassword: {{ env "MONGODB_PASSWORD" | default .StateValues.esthesisSystemPassword }}
  # esthesis UI
  - esthesisUiLogoutUrl: {{ env "ESTHESIS_UI_LOGOUT_URL" | default "/logout" }}
  - esthesisUiCertManagerClusterIssuer: {{ env "ESTHESIS_UI_CERT_MANAGER_CLUSTER_ISSUER" }}
  - esthesisUiCertManagerIssuer: {{ env "ESTHESIS_UI_CERT_MANAGER_ISSUER" }}
  # RabbitMQ
  - rabbitmqErlangCookie: {{ env "RABBITMQ_ERLANG_COOKIE" | default .StateValues.esthesisSystemUsername }}
  # Kafka
  - kafkaEnabled: {{ env "KAFKA_ENABLED" | default true }}

---
##################################################################################################
# Release definitions
##################################################################################################
releases:
  - version: "3.0.22-SNAPSHOT"
    name: esthesis-core
    chart: {{ .StateValues.devMode | ternary "./" "esthesis/esthesis-core" | quote }}
    values:
      - devMode: {{ .StateValues.devMode }}
      - timezone: {{ .StateValues.timezone | quote }}
      - esthesisRegistry: {{ .StateValues.esthesisRegistry | quote }}
      - imagePullSecret: {{ .Values.imagePullSecret | quote }}
      - quarkus:
          log:
            min-level: "TRACE"
            level: {{ .StateValues.esthesisLogLevel | quote }}
            category:
              esthesis:
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.jboss.resteasy.reactive":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.mongodb.panache.common.runtime":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.mongodb":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.oidc.token.propagation.reactive":
                level: {{ .StateValues.esthesisLogLevel | quote }}
      - esthesisAdminUsername: {{ .StateValues.esthesisAdminUsername | quote }}
      - esthesisAdminPassword: {{ .StateValues.esthesisAdminPassword | quote }}
      - esthesisSystemUsername: {{ .Values.esthesisSystemUsername | quote }}
      - esthesisSystemPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      - esthesisIngressName: {{ .StateValues.esthesisIngressName | quote }}
      - esthesisUiLogoutUrl: {{ .StateValues.esthesisUiLogoutUrl | quote }}
      # OIDC
      - oidcAuthorityUrlExternal: {{ .StateValues.oidcAuthorityUrlExternal | quote }}
      - oidcAuthorityUrlCluster: {{ .StateValues.oidcAuthorityUrlCluster | quote }}
      - oidcDiscoveryUrlCluster: {{ .StateValues.oidcDiscoveryUrlCluster | quote }}
      - oidcJwtVerifyLocationCluster: {{ .StateValues.oidcJwtVerifyLocationCluster | quote }}
      # MongoDB
      - mongoDbEnabled: {{ .StateValues.mongoDbEnabled }}
      - mongoDbUrlCluster: {{ .StateValues.mongoDbUrlCluster | quote }}
      - mongoDbDatabase: {{ .StateValues.mongoDbDatabase | quote }}
      - mongoDbUsername: {{ .StateValues.esthesisSystemUsername | quote }}
      - mongoDbPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      # REDIS
      - redisHosts: {{ .StateValues.redisHosts | quote }}
      # RabbitMQ
      - rabbitmqErlangCookie: {{ .StateValues.rabbitmqErlangCookie |quote }}
      # Camunda
      - camundaGatewayUrlCluster: {{ .StateValues.camundaGatewayUrlCluster | quote }}
      # Kafka
      - kafkaEnabled: {{ .StateValues.kafkaEnabled }}
      - kafkaBootstrapServers: {{ .StateValues.kafkaBootstrapServers | quote }}
      # Cert Manager
      - esthesisUiCertManagerClusterIssuer: {{ .StateValues.esthesisUiCertManagerClusterIssuer | quote }}
      - esthesisUiCertManagerIssuer: {{ .StateValues.esthesisUiCertManagerIssuer | quote }}


