##################################################################################################
# Environments definitions
##################################################################################################
environments:
  default:
    values:
      - devMode: false
      - redisHosts: {{ if (env "REDIS_HOSTS") }}{{ env "REDIS_HOSTS" }}{{ else }}redis://redis-headless.{{ .Namespace }}.svc.cluster.local:6379{{ end }}
      - mongoDbUrlCluster: {{ if (env "MONGODB_URL_CLUSTER") }}{{ env "MONGODB_URL_CLUSTER" }}{{ else }}mongodb://mongodb-0.mongodb-headless.{{ .Namespace }}.svc.cluster.local:27017,mongodb-1.mongodb-headless.{{ .Namespace }}.svc.cluster.local:27017{{ end }}
      - camundaGatewayUrlCluster: {{ if (env "CAMUNDA_GATEWAY_URL_CLUSTER") }}{{ env "CAMUNDA_GATEWAY_URL_CLUSTER" }}{{ else }}camunda-zeebe-gateway.{{ .Namespace }}.svc.cluster.local:26500{{ end }}
      - kafkaBootstrapServers: {{ if (env "KAFKA_BOOTSTRAP_SERVERS") }}{{ env "KAFKA_BOOTSTRAP_SERVERS" }}{{ else }}kafka.{{ .Namespace }}.svc.cluster.local:9092{{ end }}
      - oidcAuthServerUrl: {{ if (env "OIDC_AUTH_SERVER_URL") }}{{ env "OIDC_AUTH_SERVER_URL" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis{{ end }}
      - oidcClientAuthServerUrl: {{ if (env "OIDC_CLIENT_AUTH_SERVER_URL") }}{{ env "OIDC_CLIENT_AUTH_SERVER_URL" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis{{ end }}
      - esthesisReportedOidcAuthority: {{ if (env "ESTHESIS_REPORTED_OIDC_AUTHORITY_URL") }}{{ env "ESTHESIS_REPORTED_OIDC_AUTHORITY_URL" }}{{ else }}http://keycloak.{{ .Namespace }}.svc.cluster.local/realms/esthesis{{ end }}
      - esthesisReportedOidcPostLogoutUrl: {{ if (env "ESTHESIS_REPORTED_OIDC_POST_LOGOUT_URL") }}{{ env "ESTHESIS_REPORTED_OIDC_POST_LOGOUT_URL" }}{{ else }}http://esthesis-core.{{ .Namespace }}.svc.cluster.local/logout{{ end }}      
      - esthesisHostname: {{ env "ESTHESIS_HOSTNAME" }}
      - esthesisLocalCharts: {{ if (env "ESTHESIS_LOCAL_CHARTS") }}{{ env "ESTHESIS_LOCAL_CHARTS" }}{{ else }}false{{ end }}
      - oidcTlsVerification: {{ if (env "OIDC_TLS_VERIFICATION") }}{{ env "OIDC_TLS_VERIFICATION" }}{{ else }}required{{ end }}
  dev:
    values:
      - devMode: true
      - camundaGatewayUrlCluster: camunda-zeebe-gateway.{{ .Namespace }}:26500
      - kafkaBootstrapServers: kafka.{{ .Namespace }}:9094
      - redisHosts: redis://redis.{{ .Namespace }}:6379
      - oidcAuthServerUrl: http://keycloak.{{ .Namespace }}/realms/esthesis
      - oidcClientAuthServerUrl: http://keycloak.{{ .Namespace }}/realms/esthesis
      - esthesisReportedOidcAuthority: http://keycloak.{{ .Namespace }}/realms/esthesis
      - esthesisReportedOidcPostLogoutUrl: http://localhost:4200/logged-out
      - esthesisHostname: "esthesis-core.esthesis"
      - mongoDbUrlCluster: mongodb://mongodb-headless.esthesis:27017
      - esthesisLocalCharts: true
      - oidcTlsVerification: false

---
##################################################################################################
# The repositories used by this Helmfile.
##################################################################################################
repositories:
  - name: esthesis
    url: https://esthes.is/helm

---
##################################################################################################
# Default values
##################################################################################################
helmDefaults:
  timeout: 1800

---
##################################################################################################
# Default state values
##################################################################################################
values:
  - esthesisVersion: "3.1.5"
  - imagePullSecret: {{ env "IMAGE_PULL_SECRET" }}
  - timezone: {{ env "TIMEZONE" | default "Europe/Athens" }}
  - esthesisLogLevel: {{ env "ESTHESIS_LOG_LEVEL" | default "WARN" }}
  - esthesisAdminUsername: {{ env "ESTHESIS_ADMIN_USERNAME" | default "esthesis-admin" }}
  - esthesisAdminPassword: {{ env "ESTHESIS_ADMIN_PASSWORD" | default "esthesis-admin" }}
  - esthesisSystemUsername: {{ env "ESTHESIS_SYSTEM_USERNAME" | default "esthesis-system" }}
  - esthesisSystemPassword: {{ env "ESTHESIS_SYSTEM_PASSWORD" | default "esthesis-system" }}
  - esthesisRegistry: {{ env "ESTHESIS_REGISTRY_URL" }}
  - ingressClassName: {{ env "INGRESS_CLASS_NAME" }}
  - esthesisKubernetesServiceCreateRBAC: {{ env "ESTHESIS_KUBERNETES_SERVICE_CREATE_RBAC" | default true }}
  # MongoDB
  - mongoDbEnabled: {{ env "MONGODB_ENABLED" | default true }}
  - mongoDbDatabase: {{ env "MONGODB_DATABASE" | default "esthesiscore" }}
  - mongoDbUsername: {{ env "MONGODB_USERNAME" | default .StateValues.esthesisSystemUsername }}
  - mongoDbPassword: {{ env "MONGODB_PASSWORD" | default .StateValues.esthesisSystemPassword }}
  # esthesis UI
  - esthesisUiCertManagerClusterIssuer: {{ env "ESTHESIS_UI_CERT_MANAGER_CLUSTER_ISSUER" }}
  - esthesisUiCertManagerIssuer: {{ env "ESTHESIS_UI_CERT_MANAGER_ISSUER" }}
  # RabbitMQ
  - rabbitmqErlangCookie: {{ env "RABBITMQ_ERLANG_COOKIE" | default .StateValues.esthesisSystemUsername }}
  # Kafka
  - kafkaEnabled: {{ env "KAFKA_ENABLED" | default true }}
  # OIDC
  - oidcClientGrantOptionsPasswordUsername: {{ env "OIDC_CLIENT_GRANT_OPTIONS_PASSWORD_USERNAME" | default .StateValues.esthesisSystemUsername }}
  - oidcClientGrantOptionsPasswordPassword: {{ env "OIDC_CLIENT_GRANT_OPTIONS_PASSWORD_PASSWORD" | default .StateValues.esthesisSystemPassword }}
  - oidcClientId: {{ env "OIDC_CLIENT_ID" | default "esthesis" }}

---
##################################################################################################
# Release definitions
##################################################################################################
releases:
  - name: esthesis-core
    chart: {{ or .StateValues.devMode .StateValues.esthesisLocalCharts | ternary "./" "esthesis/esthesis-core" | quote }}
    version: {{ .StateValues.esthesisVersion | quote }}
    values:
      - devMode: {{ .StateValues.devMode }}
      - timezone: {{ .StateValues.timezone | quote }}
      - esthesisRegistry: {{ .StateValues.esthesisRegistry | quote }}
      - imagePullSecret: {{ .Values.imagePullSecret | quote }}
      - quarkus:
          log:
            level: {{ .StateValues.esthesisLogLevel | quote }}
            category:
              esthesis:
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.jboss.resteasy.reactive":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.mongodb.panache.common.runtime":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.mongodb":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.oidc":
                level: {{ .StateValues.esthesisLogLevel | quote }}
      - esthesisAdminUsername: {{ .StateValues.esthesisAdminUsername | quote }}
      - esthesisAdminPassword: {{ .StateValues.esthesisAdminPassword | quote }}
      - esthesisSystemUsername: {{ .Values.esthesisSystemUsername | quote }}
      - esthesisSystemPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      - esthesisHostname: {{ .StateValues.esthesisHostname | quote }}
      - ingressClassName: {{ .StateValues.ingressClassName | quote }}
      - esthesisKubernetesServiceCreateRBAC: {{ .StateValues.esthesisKubernetesServiceCreateRBAC }}
      # OIDC
      - oidcAuthServerUrl: {{ .StateValues.oidcAuthServerUrl | quote }}
      - oidcClientAuthServerUrl: {{ .StateValues.oidcClientAuthServerUrl | quote }}
      - oidcClientGrantOptionsPasswordUsername: {{ .StateValues.oidcClientGrantOptionsPasswordUsername | quote }}
      - oidcClientGrantOptionsPasswordPassword: {{ .StateValues.oidcClientGrantOptionsPasswordPassword | quote }}
      - esthesisReportedOidcAuthority: {{ .StateValues.esthesisReportedOidcAuthority | quote }}
      - esthesisReportedOidcPostLogoutUrl: {{ .StateValues.esthesisReportedOidcPostLogoutUrl | quote }}
      - oidcTlsVerification: {{ .StateValues.oidcTlsVerification }}
      - oidcClientId: {{ .StateValues.oidcClientId | quote }}
      # MongoDB
      - mongoDbEnabled: {{ .StateValues.mongoDbEnabled }}
      - mongoDbUrlCluster: {{ .StateValues.mongoDbUrlCluster | quote }}
      - mongoDbDatabase: {{ .StateValues.mongoDbDatabase | quote }}
      - mongoDbUsername: {{ .StateValues.esthesisSystemUsername | quote }}
      - mongoDbPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      # REDIS
      - redisHosts: {{ .StateValues.redisHosts | quote }}
      # RabbitMQ
      - rabbitmqErlangCookie: {{ .StateValues.rabbitmqErlangCookie |quote }}
      # Camunda
      - camundaGatewayUrlCluster: {{ .StateValues.camundaGatewayUrlCluster | quote }}
      # Kafka
      - kafkaEnabled: {{ .StateValues.kafkaEnabled }}
      - kafkaBootstrapServers: {{ .StateValues.kafkaBootstrapServers | quote }}
      # Cert Manager
      - esthesisUiCertManagerClusterIssuer: {{ .StateValues.esthesisUiCertManagerClusterIssuer | quote }}
      - esthesisUiCertManagerIssuer: {{ .StateValues.esthesisUiCertManagerIssuer | quote }}
