# Global values for the application
devMode: false
timezone: "Europe/Athens"
imagePullSecret: ""
ingressClassName: ""
ingressTlsSecret: ""

esthesisRegistry: ""
esthesisLogLevel: "WARN"
esthesisVersion: "3.0.59-SNAPSHOT"
esthesisAdminUsername: "esthesis-admin"
esthesisAdminPassword: "esthesis-admin"
esthesisSystemUsername: "esthesis-system"
esthesisSystemPassword: "esthesis-system"
esthesisHostname: ""
esthesisLocalCharts: false
esthesisKubernetesServiceCreateRBAC: true

quarkus:
  log:
    level: "WARN"
    category:
      esthesis:
        level: "WARN"
      "org.jboss.resteasy.reactive":
        level: "WARN"
      "io.quarkus.mongodb.panache.common.runtime":
        level: "WARN"
      "org.mongodb":
        level: "WARN"
      "io.quarkus.oidc":
        level: "WARN"

# MongoDB configuration
mongoDbEnabled: true
mongoDbUrlCluster: "mongodb://mongodb-0.mongodb-headless.<enter_your_namespace_here>.svc.cluster.local:27017,mongodb-1.mongodb-headless.<enter_your_namespace_here>.svc.cluster.local:27017"
mongoDbDatabase: "esthesiscore"
mongoDbUsername: "esthesis-system"
mongoDbPassword: "esthesis-system"

# OIDC configuration
oidcAuthServerUrl: "http://keycloak.<enter_your_namespace_here>.svc.cluster.local/realms/esthesis"
oidcClientAuthServerUrl: "http://keycloak.<enter_your_namespace_here>.svc.cluster.local/realms/esthesis"
oidcClientGrantOptionsPasswordUsername: "esthesis-system"
oidcClientGrantOptionsPasswordPassword: "esthesis-system"
esthesisReportedOidcAuthority: "http://keycloak.<enter_your_namespace_here>.svc.cluster.local/realms/esthesis"
esthesisReportedOidcPostLogoutUrl: "http://esthesis-core.<enter_your_namespace_here>.svc.cluster.local/logout"
oidcTlsVerification: "required"
oidcClientId: "esthesis"

# REDIS configuration
redisHosts: "redis://redis-headless.<enter_your_namespace_here>.svc.cluster.local:6379"

# RabbitMQ configuration
rabbitmqErlangCookie: "esthesis-system"

# Camunda configuration
camundaGatewayUrlCluster: "zeebe-gateway.<enter_your_namespace_here>.svc.cluster.local:26500"

# Kafka configuration
kafkaEnabled: true
kafkaBootstrapServers: "kafka.<enter_your_namespace_here>.svc.cluster.local:9092"

# Cert Manager configuration
esthesisUiCertManagerClusterIssuer: ""
esthesisUiCertManagerIssuer: ""
