# Global values for the application
devMode: true
timezone: "Europe/Athens"
imagePullSecret: ""
ingressClassName: ""
ingressTlsSecret: ""

esthesisRegistry: ""
esthesisLogLevel: "WARN"
esthesisVersion: "3.0.59-SNAPSHOT"
esthesisAdminUsername: "esthesis-admin"
esthesisAdminPassword: "esthesis-admin"
esthesisSystemUsername: "esthesis-system"
esthesisSystemPassword: "esthesis-system"
esthesisHostname: "esthesis-core.esthesis"
#esthesisLocalCharts: true
esthesisKubernetesServiceCreateRBAC: true

quarkus:
  log:
    level: "WARN"
    category:
      esthesis:
        level: "WARN"
      "org.jboss.resteasy.reactive":
        level: "WARN"
      "io.quarkus.mongodb.panache.common.runtime":
        level: "WARN"
      "org.mongodb":
        level: "WARN"
      "io.quarkus.oidc":
        level: "WARN"

# MongoDB configuration
mongoDbEnabled: true
mongoDbUrlCluster: "mongodb://mongodb-rs0:27017"
mongoDbDatabase: "esthesiscore"
mongoDbUsername: "esthesis-system"
mongoDbPassword: "esthesis-system"

# OIDC configuration
oidcAuthServerUrl: "http://keycloak/realms/esthesis"
oidcClientAuthServerUrl: "http://keycloak/realms/esthesis"
oidcClientGrantOptionsPasswordUsername: "esthesis-system"
oidcClientGrantOptionsPasswordPassword: "esthesis-system"
esthesisReportedOidcAuthority: "http://keycloak/realms/esthesis"
esthesisReportedOidcPostLogoutUrl: "http://localhost:4200/logged-out"
oidcTlsVerification: false
oidcClientId: "esthesis"

# REDIS configuration
redisHosts: "redis://redis:6379"

# RabbitMQ configuration
rabbitmqErlangCookie: "esthesis-system"

# Camunda configuration
camundaGatewayUrlCluster: "zeebe-gateway:26500"

# Kafka configuration
kafkaEnabled: true
kafkaBootstrapServers: "kafka-kafka-bootstrap:9092"

# Cert Manager configuration
esthesisUiCertManagerClusterIssuer: ""
esthesisUiCertManagerIssuer: ""

# Chatbot configuration
chatbot:
  service:
    enabled: false
  chatModel:
    provider: "ollama"
  embeddingModel:
    provider: "ollama"
  easyRag:
    path: "rag"
    pathType: "classpath"
  openai:
    apiKey: "change-me"
    chatModel:
      modelName: "gpt-3.5-turbo"
      temperature: 0.1
  ollama:
    baseUrl: "http://ollama:11434"
    timeout: "60s"
    chatModel:
      modelId: "qwen3:0.6b"
      temperature: 0.1
    embeddingModel:
      modelId: "nomic-embed-text"
      temperature: 0.1
