apiVersion: v2
name: esthesis-edge
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: "1.0.0-SNAPSHOT"
appVersion: "1.0.0-SNAPSHOT"
