{{- if .Values.mosquittoEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:2.0.15
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8883
              name: mqtts
            - containerPort: 9001
              name: ws
          startupProbe:
            tcpSocket:
              {{- if .Values.mosquittoMutualTls }}
              port: 8883
              {{- else }}
              port: 1883
              {{- end }}
          livenessProbe:
            tcpSocket:
              {{- if .Values.mosquittoMutualTls }}
              port: 8883
              {{- else }}
              port: 1883
              {{- end }}
          volumeMounts:
            - name: mosquitto-persistent-storage
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            {{- if .Values.mosquittoMutualTls }}
            - name: mosquitto-acl
              mountPath: /mosquitto/secret
            {{- end}}
      volumes:
        - name: mosquitto-persistent-storage
          persistentVolumeClaim:
            claimName: mosquitto
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        {{- if .Values.mosquittoMutualTls }}
        - name: mosquitto-acl
          secret:
            secretName: mosquitto-acl
            items:
              - key: ca.crt
                path: ca.crt
              - key: server.crt
                path: server.crt
              - key: server.key
                path: server.key
              - key: aclfile.conf
                path: aclfile.conf
        {{- end }}
{{- end}}
