{{- if .Values.mosquittoEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password
  labels:
    app: mosquitto
type: Opaque
stringData:
  password.txt: |
    admin:$7$101$tz6arXoVTIHSiOis$msNpyhYVntBTDtPjHeUhr8YAckwsKfQRivH9hm+It7Bn3/1OB2aBHQq+S0n5AZMokqRtv79Rzh5oZMwnnhtXZw==
{{- end }}
