{{- if .Values.mosquittoEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    app.kubernetes.io/name: mosquitto

spec:
  type: {{ .Values.mosquittoServiceType }}
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqtts
    - port: 9001
      name: ws
  selector:
    app: mosquitto
{{- end }}
