{{- if .Values.mosquittoEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    app.kubernetes.io/name: mosquitto

spec:
  type: {{ .Values.mosquittoServiceType }}
  ports:
    {{- if .Values.mosquittoMutualTls }}
    - port: 8883
      name: mqtts
    {{- else }}
    - port: 1883
      name: mqtt
    {{- end }}
  selector:
    app: mosquitto
{{- end }}
