apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Namespace }}-{{ .Values.backupPVC.claimName }}
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "{{ .Values.backupPVC.storageClassName }}" # required for static provisioning
  resources:
    requests:
      storage: {{ .Values.backupPVC.storage }} # ignored, required
  volumeName: {{ .Values.backupPVC.volumeName }}
