{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "utility.safeName" .Release.Namespace "-esthesis-core-srv-kubernetes-cluster-role" }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{ end }}
