{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "utility.safeName" .Release.Namespace "-esthesis-core-srv-kubernetes-cluster-role-binding" }}
subjects:
- kind: ServiceAccount
  name: esthesis-core-srv-kubernetes
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "utility.safeName" .Release.Namespace "-esthesis-core-srv-kubernetes-cluster-role" }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
