{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "esthesis-core-srv-kubernetes-cluster-role" | trunc 63 | trimSuffix "-" }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{ end }}
