{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "esthesis-core-srv-kubernetes-cluster-role-binding" | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: esthesis-core-srv-kubernetes
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-%s" .Release.Namespace "esthesis-core-srv-kubernetes-cluster-role" | trunc 63 | trimSuffix "-" }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
