{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: esthesis-core-srv-kubernetes-role-binding
subjects:
  - kind: ServiceAccount
    name: esthesis-core-srv-kubernetes
roleRef:
  kind: Role
  name: esthesis-core-srv-kubernetes-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
