{{ if .Values.esthesisKubernetesServiceCreateRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: esthesis-core-srv-kubernetes-role
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "update", "patch", "delete"]
{{ end }}
