{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podName" "esthesis-core-srv-infrastructure"
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podJwtVerifier" true
  "podMongoDb" true
  "podLogging" true
  "podProbes" true
  "podKafka" true
  "podOidcClient" true
) .) }}
{{ end }}
