{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podJwtVerifier" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" false
  "podName" "esthesis-core-srv-dt"
  "podOidcClient" true
  "podProbes" true
  "podRedis" true
) .) }}
{{ end }}
