{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podJwtVerifier" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" true
  "podName" "esthesis-core-srv-application"
  "podProbes" true
  "podRedis" true
  "registry" .Values.esthesisRegistry
  "timezone" .Values.timezone
) .) }}
{{ end }}
