{{ if and (not .Values.devMode) .Values.chatbot.service.enabled }}
{{ template "deployment.api.template" (merge (dict
  "podOidc" true
  "podOidcClient" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "1G"
  "podName" (include "chatbotImage" .)
  "podProbes" true
  "podChatbot" true
  "registry" .Values.esthesisRegistry
  "timezone" .Values.timezone
  "imagePullSecret" .Values.imagePullSecret
) .) }}
{{ end }}
