##################################################################################################
# The repositories used by this Helmfile.
##################################################################################################
repositories:
  - name: esthesis
    url: https://esthes.is/helm

---
##################################################################################################
# Default values
##################################################################################################
helmDefaults:
  timeout: 1800

---
##################################################################################################
# Default state values
##################################################################################################
values:
  ##################################################################################################
  # Chart-specific values.
  ##################################################################################################
  - esthesisVersion: "3.0.39"
  - mongodbname: {{ env "ESTHESIS_BACKUP_MONGODB_CRONJOB_NAME" | default "esthesis-mongodb-backup-cronjob" }}
  - mongodbuser: {{ env "ESTHESIS_BACKUP_MONGODB_USER" | default "root" }}
  - mongodbsecretName: {{ env "ESTHESIS_BACKUP_MONGODB_SECRET | default "my-mongodb" }}
  - mongodbhost: {{ env "ESTHESIS_BACKUP_MONGODB_HOST" | default "my-mongodb" }}
  - mongodbport: {{ env "ESTHESIS_BACKUP_MONGODB_PORT | default "27017" }}
  - mongodbschedule: {{ env "ESTHESIS_BACKUP_MONGODB_SCHEDULE" | default "0 2 * * *" }}
  - mongodbsubPath: {{ env "ESTHESIS_BACKUP_MONGODB_PATH" | default "backup/mongodb" }}

  - influxdbname: {{ env "ESTHESIS_BACKUP_INFLUXDB_CRONJOB_NAME" | default "esthesis-influxdb-backup-cronjob" }}
  - influxdbsecretName: {{ env "ESTHESIS_BACKUP_INFLUXDB_SECRET | default "my-influxdb" }}
  - influxdbhost: {{ env "ESTHESIS_BACKUP_INFLUXDB_HOST" | default "my-influxdb" }}
  - influxdbport: {{ env "ESTHESIS_BACKUP_INFLUXDB_PORT | default "8086" }}
  - influxdbschedule: {{ env "ESTHESIS_BACKUP_INFLUXDB_SCHEDULE" | default "0 2 * * *" }}
  - influxdbsubPath: {{ env "ESTHESIS_BACKUP_INFLUXDB_PATH" | default "backup/influxdb" }}

  - claimName: {{ env "ESTHESIS_BACKUP_PVC_NAME" | default "esthesis-backup-s3-claim" }}
  - volumeName: {{ env "ESTHESIS_BACKUP_VOLUME_NAME" | default "esthesis-backup-s3-pv" }}
  - storageClassName: {{ env "ESTHESIS_BACKUP_STORAGE_CLASS_NAME" | default ""}}
  - storage: {{ env "ESTHESIS_BACKUP_STORAGE" | default "10Gi" }}
---
##################################################################################################
# Release definitions
##################################################################################################
releases:
  - name: esthesis-core-backups
    chart: "esthesis/esthesis-core-backups"
    version: {{ .StateValues.esthesisVersion | quote }}
    values:
      # MongoDB
      - mongodb:
          name: {{ .StateValues.mongodbname | quote }}
          mongouser: {{ .StateValues.mongodbuser | quote }}
          secretName: {{ .StateValues.mongodbsecretName | quote }}
          host: {{ .StateValues.mongodbhost | quote }}
          port: {{ .StateValues.mongodbport | quote }}
          schedule: {{ .StateValues.mongodbschedule | quote }}
          subPath: {{ .StateValues.mongodbsubPath | quote }}
      # InfluxDB
      - influxdb:
          name: {{ .StateValues.influxdbname | quote }}
          secretName: {{ .StateValues.influxdbsecretName | quote }}
          host: {{ .StateValues.influxdbhost | quote }}
          port: {{ .StateValues.influxdbport | quote }}
          schedule: {{ .StateValues.influxdbschedule | quote }}
          subPath: {{ .StateValues.influxdbsubPath | quote }}
      # Backup PVC
      - backupPVC:
          claimName: {{ .StateValues.claimName | quote }}
          volumeName: {{ .StateValues.volumeName | quote }}
          storageClassName: {{ .StateValues.storageClassName | quote }}
          storage: {{ .StateValues.storage | quote }}
