mongodb:
  name: {{ env "ESTHESIS_BACKUP_MONGODB_CRONJOB_NAME" | default "esthesis-mongodb-backup-cronjob" }}
  mongouser: {{ env "ESTHESIS_BACKUP_MONGODB_USER" | default "root" }}
  secretName: {{ env "ESTHESIS_BACKUP_MONGODB_SECRET | default "my-mongodb" }}
  host: {{ env "ESTHESIS_BACKUP_MONGODB_HOST" | default "my-mongodb" }}
  port: {{ env "ESTHESIS_BACKUP_MONGODB_PORT | default "27017" }}
  schedule: {{ env "ESTHESIS_BACKUP_MONGODB_SCHEDULE" | default "0 2 * * *" }}
  subPath: {{ env "ESTHESIS_BACKUP_MONGODB_PATH" | default "backup/mongodb" }}

influxdb:
  name: {{ env "ESTHESIS_BACKUP_INFLUXDB_CRONJOB_NAME" | default "esthesis-influxdb-backup-cronjob" }}
  secretName: {{ env "ESTHESIS_BACKUP_INFLUXDB_SECRET | default "my-influxdb" }}
  host: {{ env "ESTHESIS_BACKUP_INFLUXDB_HOST" | default "my-influxdb" }}
  port: {{ env "ESTHESIS_BACKUP_INFLUXDB_PORT | default "8086" }}
  schedule: {{ env "ESTHESIS_BACKUP_INFLUXDB_SCHEDULE" | default "0 2 * * *" }}
  subPath: {{ env "ESTHESIS_BACKUP_INFLUXDB_PATH" | default "backup/influxdb" }}

backupPVC:
  claimName: {{ env "ESTHESIS_BACKUP_PVC_NAME" | default "esthesis-backup-s3-claim" }}
  volumeName: {{ env "ESTHESIS_BACKUP_VOLUME_NAME" | default "esthesis-backup-s3-pv" }}
  storageClassName: {{ env "ESTHESIS_BACKUP_STORAGE_CLASS_NAME" | default ""}}
  storage: {{ env "ESTHESIS_BACKUP_STORAGE" | default "10Gi" }}
