global:
  namespace: "test-s3-backups"

mongodb:
  name: "mongodb-backup"
  mongouser: "root"
  secretName: "my-mongodb"
  host: "my-mongodb"
  port: "27017"
  schedule: "0 2 * * *"
  subPath: "backup/mongodb"

influxdb:
  name: "influxdb-backup"
  secretName: "my-influxdb"
  host: "my-influxdb"
  port: "8086"
  schedule: "0 2 * * *"
  subPath: "backup/influxdb"

backupPVC:
  claimName: "backup-s3-claim"
  volumeName: "backup-s3-pv"
  storageClassName: "" ## Leave empty for S3
  storage: "10Gi"
