{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podName" "esthesis-core-srv-agent"
  "podOidcClient" true
  "podProbes" true
  "podRedis" true
  "registry" .Values.esthesisRegistry
  "timezone" .Values.timezone
  "imagePullSecret" .Values.imagePullSecret
) .) }}
{{ end }}
