{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podJwtVerifier" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" true
  "podName" "esthesis-core-srv-security"
  "podOidcClient" true
  "podProbes" true
  "timezone" .Values.timezone
  "registry" .Values.esthesisRegistry
  "extraEnvVars" (dict
    "ESTHESIS_SECURITY_ADMIN_USERNAME" .Values.esthesisAdminUsername
  )
) .) }}
{{ end }}
