apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-krakend-cm
  labels:
    name: {{ .Release.Name }}-krakend-cm
data:
  krakend.json: |
    {{- tpl ($.Files.Get "config/krakend.json") . | nindent 4 }}
