apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-krakend-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-krakend
