{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podOidc" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" true
  "podName" "esthesis-core-srv-kubernetes"
  "podProbes" true
  "registry" .Values.esthesisRegistry
  "serviceAccountName" "esthesis-core-srv-kubernetes"
  "timezone" .Values.timezone
  "imagePullSecret" .Values.imagePullSecret
) .) }}
{{ end }}
