{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podJwtVerifier" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" true
  "podName" "esthesis-core-srv-kubernetes"
  "podProbes" true
) .) }}
{{ end }}
