{{ if not .Values.devMode }}
{{ template "deployment.api.template" (merge (dict
  "podOidc" true
  "podKafka" true
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "512M"
  "podMongoDb" true
  "podName" "esthesis-core-srv-tag"
  "podProbes" true
  "registry" .Values.esthesisRegistry
  "timezone" .Values.timezone
  "imagePullSecret" .Values.imagePullSecret
) .) }}
{{ end }}
