{{- if .Values.devMode }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-loki-config
type: Opaque
stringData:
  promtail.yaml: |-
    server:
      log_level: warn
      http_listen_port: 8080
    clients:
      - url: http://grafana-loki-distributor:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
      - job_name: gelf
        gelf:
          listen_address: "0.0.0.0:12201"
          use_incoming_timestamp: true
        relabel_configs:
          - action: replace
            source_labels:
              - __gelf_message_host
            target_label: host
          - action: replace
            source_labels:
              - __gelf_message_level
            target_label: level
          - action: replace
            source_labels:
              - _platform
            target_label: platform
          - action: replace
            source_labels:
              - _module
            target_label: module
          - action: replace
            source_labels:
              - _type
            target_label: type
          - action: replace
            source_labels:
              - _service
            target_label: service
{{- end }}
