{{ if not .Values.devMode }}
{{ $redirectUrl := print "https://" .Values.esthesisUiIngressHostname "/callback" }}
{{ template "deployment.api.template" (merge (dict
  "podJwtVerifier" false
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podMongoDb" false
  "podName" "esthesis-core-srv-public-access"
  "podOidcClient" false
  "podProbes" true
  "timezone" .Values.timezone
  "registry" .Values.esthesisRegistry
  "extraEnvVars" (dict
    "ESTHESIS_OIDC_AUTHORITY" .Values.oidcAuthorityUrlExternal
    "ESTHESIS_OIDC_REDIRECT_URL" $redirectUrl
    "ESTHESIS_OIDC_POST_LOGOUT_REDIRECT_URI" .Values.esthesisUiLogoutUrl
  )
) .) }}
{{ end }}
