{{ if not .Values.devMode }}
{{ $redirectUrl := print "http://" .Values.esthesisHostname "/callback" }}
{{ template "deployment.api.template" (merge (dict
  "podLogging" true
  "podMaxCpu" "1"
  "podMaxMemory" "256M"
  "podName" "esthesis-core-srv-public-access"
  "podProbes" true
  "registry" .Values.esthesisRegistry
  "timezone" .Values.timezone
  "imagePullSecret" .Values.imagePullSecret
  "extraEnvVars" (dict
    "ESTHESIS_OIDC_AUTHORITY" .Values.esthesisReportedOidcAuthority
    "ESTHESIS_OIDC_REDIRECT_URL" $redirectUrl
    "ESTHESIS_OIDC_POST_LOGOUT_REDIRECT_URI" .Values.esthesisReportedOidcPostLogoutUrl
  )
) .) }}
{{ end }}
