apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-srv-public-access-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-srv-public-access
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-srv-public-access
    spec:
      containers:
        - name: esthesis-core-srv-public-access
          image: esthesisiot/esthesis-core-srv-public-access:3.0.0-SNAPSHOT
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.25"
              memory: "128M"
            limits:
              cpu: "1"
              memory: "256M"
          ports:
            - containerPort: 8080
