apiVersion: v1
kind: Service
metadata:
  name: esthesis-edge-service
spec:
  type: {{ .Values.esthesis.edge.service.type }}
  ports:
    - name: http
      port: {{ .Values.esthesis.edge.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: esthesis-edge
